MAGICLOOPS_API_KEY = "https://magicloops.dev/api/loop/cab52eb1-35de-4b59-bdcd-8260934ccb6d/run"
DROPBOX_DB_URL = "https://www.dropbox.com/scl/fi/c6m8x5i5ixvti92qtyrhu/automotor.db?rlkey=kg5ghe5zzkg0bjec23011iof5&st=gpqpt3op&dl=1"